#!/bin/sh

java_cmd="java -classpath /home/aurelien/Documents/travail/2A/28-SLR210/project/SLR210OFC/target/classes:/home/aurelien/.m2/repository/com/typesafe/akka/akka-actor_2.12/2.5.22/akka-actor_2.12-2.5.22.jar:/home/aurelien/.m2/repository/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar:/home/aurelien/.m2/repository/com/typesafe/config/1.3.3/config-1.3.3.jar:/home/aurelien/.m2/repository/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar Main"

for i in 0 1 2 3 4
do
	echo -e "======================\n$i-th run"
	for nProcesses in 3 10 100
	do
		for tL in 500 1000 1500 2000
		do
			nFaulty=0
			if [ $nProcesses -eq 3 ]
			then
				nFaulty=1	
			elif [ $nProcesses -eq 10 ]
			then
				nFaulty=4
			else
				nFaulty=49
			fi
			echo "test with $nProcesses processes, $nFaulty faulty, $tL time"

			(eval "$java_cmd $nProcesses $nFaulty $tL") > "tests_results/res_${nProcesses}_${nFaulty}_${tL}_$i"
		done
	done
done
